### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by y368413** [mynian/ConvertRatings#10] opened 2017-03-02 13:58 UTC
Interface\AddOns\ConvertRatings\ConvertRatings.lua:142: Usage: GetItemInfo(itemID|"name"|"itemlink")
Count: 2

Call Stack:
[C]: ?
[C]: in function `GetItemInfo'
Interface\AddOns\ConvertRatings\ConvertRatings.lua:142: in function <Interface\AddOns\ConvertRatings\ConvertRatings.lua:114>
[C]: ?
[C]: in function `SetCompareItem'
Interface\FrameXML\GameTooltip.lua:282: in function `GameTooltip_ShowCompareItem'
[string "*:OnTooltipSetItem"]:3: in function <[string "*:OnTooltipSetItem"]:1>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetBagItem'
Interface\FrameXML\ContainerFrame.lua:1149: in function `ContainerFrameItemButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

**Comment by mynian** [comment] 2017-03-02 14:38
What were you doing when you received this error? Were you mousing over something specific or are you getting it all the time? Need a little more info to investigate.

**Comment by y368413** [comment] 2017-03-02 14:41
1、log in
2、open bags
3、move mouse on weapons
4、bugs show

I set the CVar：  SetCVar("alwaysCompareItems", 1)

**Comment by mynian** [comment] 2017-03-04 02:06
i set the cvar as you did, logged in and moused over the other artifact weapons in my bag, did not get the error you reported. I don't have any non artifact weapons currently, I will go kill some old bosses and see if the error occurs with non artifact weapons

**Comment by mynian** [comment] 2017-03-04 03:21
i went and acquired some non artifact weapons, i tried with artifact equipped and non artifact mouse-over, non artifact equipped, and mouse-over artifact, non artifact equipped and non artifact mouse-over. Unable to reproduce this error

Are you sure it was from mousing over a weapon?

**Comment by y368413** [comment] 2017-03-04 03:57
Sure。
And ，I Finally found Is “ztip”·s problem   --ztip is a mousetooltip addon
Truly sorry。。

**Comment by mynian** [comment] 2017-03-04 03:58
no problem, closing ticket

**Closed as completed by mynian** 2017-03-04 03:58 UTC
Labels: invalid, unabletoreproduce
