### ISSUE TITLE
Toy Box Tooltip Error

### ISSUE THREAD

**Issue by QmlnIENodW5ndXM** [mynian/ConvertRatings#12] opened 2017-03-19 21:14 UTC
2x ConvertRatings\ConvertRatings-1.8.lua:142: Usage: GetItemInfo(itemID|"name"|"itemlink")
[C]: in function `GetItemInfo'
ConvertRatings\ConvertRatings-1.8.lua:142: in function <ConvertRatings\ConvertRatings.lua:114>
[C]: ?
...rfaceTradeSkillMaster\Private\TooltipLib.lua:85: in function <...rfaceTradeSkillMaster\Private\TooltipLib.lua:82>
[C]: in function `SetToyByItemID'
...faceBlizzard_Collections\Blizzard_ToyBox.lua:126: in function <...faceBlizzard_Collections\Blizzard_ToyBox.lua:124>

Locals:
(*temporary) = nil

**Comment by mynian** [comment] 2017-03-19 21:46
i opened up my toy box and moused over every item, (learned or unlearned) and was unable to get any errors.

It looks like you have another addon contributing to this error, I can't really tell what addon since the name got cut off in your post, but it looks like TradeSkillMaster or one of its plugins. 

If you have that installed, disable it and see if the error persists and report back

**Comment by mynian** [comment] 2017-03-22 20:14
Since I have not received any follow-up, I am going to assume that the error was caused by the additional addon and will be closing this issue.

**Closed as completed by mynian** 2017-03-22 20:14 UTC
Labels: unabletoreproduce
