### ISSUE TITLE
Auction House tooltip error

### ISSUE THREAD

**Issue by QmlnIENodW5ndXM** [mynian/ConvertRatings#11] opened 2017-03-19 21:13 UTC
2x ConvertRatings\ConvertRatings-1.8.lua:142: Usage: GetItemInfo(itemID|"name"|"itemlink")
[C]: in function `GetItemInfo'
ConvertRatings\ConvertRatings-1.8.lua:142: in function <ConvertRatings\ConvertRatings.lua:114>
[C]: ?
...rfaceTradeSkillMaster\Private\TooltipLib.lua:85: in function <...rfaceTradeSkillMaster\Private\TooltipLib.lua:82>
[C]: ?
[C]: ?
...rfaceTradeSkillMaster\Private\TooltipLib.lua:95: in function `SetAuctionSellItem'
Auctionator\Auctionator-4.0.16.lua:1218: in function `Atr_GetSellItemInfo'
Auctionator\Auctionator-4.0.16.lua:3112: in function `Atr_SetDepositText'
Auctionator\Auctionator-4.0.16.lua:3072: in function `Atr_UpdateUI_SellPane'
Auctionator\Auctionator-4.0.16.lua:3009: in function `Atr_UpdateUI'
Auctionator\Auctionator-4.0.16.lua:2847: in function `Atr_Idle'
Auctionator\Auctionator-4.0.16.lua:2796: in function `Atr_OnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
(*temporary) = nil

**Comment by mynian** [comment] 2017-03-19 21:47
i opened up the auction house, and did a bunch of searches for various items and got no errors.

It looks like you have another addon contributing to this error, I can't really tell what addon since the name got cut off in your post, but it looks like TradeSkillMaster or one of its plugins.

If you have that installed, disable it and see if the error persists and report back

**Comment by mynian** [comment] 2017-03-22 20:14
Since I have not received any follow-up, I am going to assume that the error was caused by the additional addon and will be closing this issue.

**Closed as completed by mynian** 2017-03-22 20:14 UTC
Labels: unabletoreproduce
