### ISSUE TITLE
Not working for 10.0.2

### ISSUE THREAD

**Issue by lowpita** [mynian/ConvertRatings#40] opened 2022-11-16 11:29 UTC
Hey. As of today's retail update (10.0.2) this addon is not working anymore and is throwing the following error: 

6x Interface/AddOns/ConvertRatings/ConvertRatings.lua:2168: GameTooltip doesn't have a "OnTooltipSetItem" script
[string "=[C]"]: in function `?'
[string "@Interface/AddOns/ConvertRatings/ConvertRatings.lua"]:2168: in main chunk

Locals:
(*temporary) = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestPartyProgress = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessLineData = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:303
 SetPvpTalent = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRuneforgeResultItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetHyperlink = <function> defined =[C]:-1
 SetUnit = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAzeriteEssence = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidDepositItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidWithdrawalItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetInfoBackdropStyle = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:338
 shoppingTooltips = <table> {
 }
 SetSocketGem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 updateTooltipTimer = 0.200000
 ItemTooltip = Frame {
 }
 StatusBar = GameTooltipStatusBar {
 }
 SetLootCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetSlottedKeystone = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetWorldCursor = <function> defined @Interface/FrameXML/GameTooltip.lua:952
 SetLootItem = <function> defined =[C]:-1
 SetMerchantCostItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 GetUnit = <function> defined @Interface/FrameXML/GameTooltip.lua:994
 SetOwnedItemByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetItemInteractionItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestLogSpecialItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 TextRight1 = GameTooltipTextRight1 {
 }
 SetEnhancedConduit = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetQuestCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 supportsDataRefresh = true
 SetWeeklyReward = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMerchantItem = <function> defined =[C]:-1
 SetPvpBrawl = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAchievementByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 BottomOverlay = Texture {
 }
 SetSpellByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 supportsItemComparison = true
 SetSocketedRelic = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236
 ProcessLines = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:293
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined =[C]:-1
 RefreshData = <function> defined @Interface/FrameXML/GameTooltip.lua:933
 SetTransmogrifyItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLootRollItem = <function> defined =[C]:-1
 OnLoad = <function> defined @Interface/FrameXML/GameTooltip.lua:927
 SetQuestLogCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitDebuffByAuraInstanceID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBagItem = <function> defined =[C]:-1
 GetSpell = <function> defined @Interface/FrameXML/GameTooltip.lua:990
 SetAction = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetItemKey = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetCompanionPet = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetInventoryItemByID = <function

**Comment by mynian** [comment] 2022-11-16 17:56
apparently they dun gone and fucking rewrote how tooltips work. This may take a while to fix.

**Comment by mynian** [comment] 2022-11-17 11:49
Partial fix included in latest release to get the addon mostly working.

You will get an error when you have an item comparison tooltip showing and no conversions in the item comparison tooltip with this version. I am currently attempting to work out how to fix that last part.

**Comment by lowpita** [comment] 2022-11-17 23:19
Hey. Thank you for the update. As of the tooltip without comparing items it's working fine. I got this error just as loading into the game without doing any item comparion, so I think it's no related to it:

12x Interface/AddOns/ConvertRatings/ConvertRatings.lua:2021: attempt to index local 'line' (a nil value)
[string "@Interface/AddOns/ConvertRatings/ConvertRatings.lua"]:2021: in function <Interface/AddOns/ConvertRatings/ConvertRatings.lua:228>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `resume'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1189: in function `Login'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1273: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1224>

Locals:
self = WeakAurasTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestPartyProgress = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessLineData = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:303
 SetPvpTalent = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRuneforgeResultItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetHyperlink = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnit = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAzeriteEssence = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidDepositItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidWithdrawalItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetInfoBackdropStyle = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:338
 hasMoney = 1
 shownMoneyFrames = 1
 SetSocketGem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 numMoneyFrames = 1
 info = <table> {
 }
 updateTooltipTimer = 0.200000
 SetLootCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetSlottedKeystone = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetWorldCursor = <function> defined @Interface/FrameXML/GameTooltip.lua:952
 SetLootItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 StatusBar = WeakAurasTooltipStatusBar {
 }
 GetUnit = <function> defined @Interface/FrameXML/GameTooltip.lua:994
 SetOwnedItemByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMerchantCostItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestLogSpecialItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetItemInteractionItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 TextRight1 = WeakAurasTooltipTextRight1 {
 }
 SetRecipeReagentItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetEnhancedConduit = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetWeeklyReward = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMerchantItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetPvpBrawl = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAchievementByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 BottomOverlay = Texture {
 }
 SetSpellByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 supportsDataRefresh = true
 SetSocketedRelic = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236
 ProcessLines = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:293
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 RefreshData = <function> defined @Interface/FrameXML/GameTooltip.lua:933
 SetTransmogrifyItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLootRollItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 OnLoad = <function> defined @Interface/FrameXML/GameTooltip.lua:927
 SetQuestLogCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitDebuffByAuraInstanceID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBagItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 GetSpell = <function> defined @Interface/Fra
 
 This is the error I got when trying to compare items:
 
 86x Interface/AddOns/ConvertRatings/ConvertRatings.lua:296: attempt to call method 'GetItem' (a nil value)
[string "@Interface/AddOns/ConvertRatings/ConvertRatings.lua"]:296: in function <Interface/AddOns/ConvertRatings/ConvertRatings.lua:228>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=[C]"]: in function `ProcessInfo'
...
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:135: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1504: in function `UpdateTooltip'
[string "@Interface/FrameXML/GameTooltip.lua"]:498: in function <Interface/FrameXML/GameTooltip.lua:491>
[string "=[C]"]: ?

Locals:
self = ShoppingTooltip1 {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetSocketGem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 SetLootCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLootItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 ttGradient = Texture {
 }
 SetQuestLogSpecialItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 BottomOverlay = Texture {
 }
 SetSocketedRelic = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessInfo = <function> defined =[C]:-1
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 TopEdge = Texture {
 }
 SetUnitDebuffByAuraInstanceID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBagItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBackdropColor = <function> defined @Interface/AddOns/TipTac/ttCore.lua:1692
 LeftEdge = Texture {
 }
 SetCurrencyByID = <function> defined =[C]:-1
 SetSpellBookItem = <function> defined =[C]:-1
 textLeft1Font = "GameFontNormalSmall"
 SetShapeshift = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetArtifactPowerByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 textRight2Font = "GameFontHighlightSmall"
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitDebuff = <function> defined =[C]:-1
 SetMountBySpellID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 SetToyByItemID = <function> defined =[C]:-1
 TextLeft1 = ShoppingTooltip1TextLeft1 {
 }
 GetTooltipData = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:344
 SetLFGDungeonShortageReward = <function> defined =[C]:-1
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 SetArtifactItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetPossession = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAzeriteEssenceSlot = <function> defined =[C]:-1
 SetUnitBuffByAuraInstanceID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetConduit = <function> defined =[C]:-1
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetMinimapMouseover = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestLogCurrency = <function> defined =[C]:-1
 SetRecipeResultItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestPartyProgress = <function> defined =[C]:-1
 ProcessLineData = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:303
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 SetPvpTalent = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRuneforgeResultItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnit = <function> defined =[C]:-1
 SetTotem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidWithdrawalItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 ttSetBackdropBorderColorLocked = true
 SetInfoBackdropStyle = <function> de

**Comment by mynian** [comment] 2022-11-17 23:47
The first error you got is most likely caused by a specific WeakAura that you are using. I have WeakAuras installed and running and I don't get that error when I log in.

The second error is the known issue that I am attempting to try and figure out how to solve.

**Comment by mynian** [comment] 2022-11-19 20:27
Comparison tooltips should be fixed in latest release.

Not sure about your weakaura error though

**Closed as completed** 2022-11-20 12:21 UTC
Labels: bug
